### ISSUE TITLE
Wrong shell

### ISSUE THREAD

**Issue by polluks** [rice7th/swef#6] opened 2022-06-16 22:11 UTC
macOS uses zsh
```
  __()_         os: Mac Os
.'     '.       wm: Quartz Compositor
|      (        kn: Darwin 21.5.0
'._____.'       sh: sh
```
```zsh
$ echo $SHELL
/bin/zsh
```

**Comment by rice7th** [comment] 2022-08-02 21:33
This is a common bug caused by the $SHELL variable. I will look forward and fix that.

**Comment by rice7th** [comment] 2022-08-05 11:40
should be fixed now

**Comment by rice7th** [comment] 2022-08-05 13:03
Okay, so, the bug was the fact that in swef, if the basename program is not found, then it will fallback to ```sh```. Now if there is no basename, it will just display $SHELL. This means that you will get ```/bin/zsh``` instead of ```zsh```

**Closed as completed by rice7th** 2022-08-05 13:03 UTC

**Comment by polluks2** [comment] 2022-08-05 17:00
thx!
